name: Generate contribution graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate contribution graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: zainkhan-pro
          outputs: |
            dist/github-contribution-snake.svg?palette=github-light
            dist/github-contribution-snake-dark.svg?palette=github-dark

      - name: Publish graph
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
